// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type Options } from '@hey-api/client-fetch';
import type { GetCommandsError, GetCommandsResponse, ExecuteCommandData, ExecuteCommandError, ExecuteCommandResponse, PingError, PingResponse, WhatsMyNameError, WhatsMyNameResponse, WhatsTheTimeMrWolfError, WhatsTheTimeMrWolfResponse, WhoAmIError, WhoAmIResponse } from './types.gen';

export const client = createClient(createConfig());

export class KeystoneService {
    public static getCommands<ThrowOnError extends boolean = false>(options?: Options<unknown, ThrowOnError>) {
        return (options?.client ?? client).get<GetCommandsResponse, GetCommandsError, ThrowOnError>({
            ...options,
            url: '/umbraco/keystone/api/v1/commands'
        });
    }
    
    public static executeCommand<ThrowOnError extends boolean = false>(options?: Options<ExecuteCommandData, ThrowOnError>) {
        return (options?.client ?? client).post<ExecuteCommandResponse, ExecuteCommandError, ThrowOnError>({
            ...options,
            url: '/umbraco/keystone/api/v1/execute'
        });
    }
    
    public static ping<ThrowOnError extends boolean = false>(options?: Options<unknown, ThrowOnError>) {
        return (options?.client ?? client).get<PingResponse, PingError, ThrowOnError>({
            ...options,
            url: '/umbraco/keystone/api/v1/ping'
        });
    }
    
    public static whatsMyName<ThrowOnError extends boolean = false>(options?: Options<unknown, ThrowOnError>) {
        return (options?.client ?? client).get<WhatsMyNameResponse, WhatsMyNameError, ThrowOnError>({
            ...options,
            url: '/umbraco/keystone/api/v1/whatsMyName'
        });
    }
    
    public static whatsTheTimeMrWolf<ThrowOnError extends boolean = false>(options?: Options<unknown, ThrowOnError>) {
        return (options?.client ?? client).get<WhatsTheTimeMrWolfResponse, WhatsTheTimeMrWolfError, ThrowOnError>({
            ...options,
            url: '/umbraco/keystone/api/v1/whatsTheTimeMrWolf'
        });
    }
    
    public static whoAmI<ThrowOnError extends boolean = false>(options?: Options<unknown, ThrowOnError>) {
        return (options?.client ?? client).get<WhoAmIResponse, WhoAmIError, ThrowOnError>({
            ...options,
            url: '/umbraco/keystone/api/v1/whoAmI'
        });
    }
    
}